package com.github.hirsivaja.ip.icmpv6;

public enum Icmpv6Codes implements Icmpv6Code {
    NO_ROUTE_TO_DESTINATION(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 0),
    COMMUNICATION_WITH_DESTINATION_ADMINISTRATIVELY_PROHIBITED(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 1),
    BEYOND_SCOPE_OF_SOURCE_ADDRESS(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 2),
    ADDRESS_UNREACHABLE(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 3),
    PORT_UNREACHABLE(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 4),
    SOURCE_ADDRESS_FAILED_INGRESS_OR_EGRESS_POLICY(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 5),
    REJECT_ROUTE_TO_DESTINATION(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 6),
    ERROR_IN_SOURCE_ROUTING_HEADER(Icmpv6Types.DESTINATION_UNREACHABLE, (byte) 7),
    PACKET_TOO_BIG(Icmpv6Types.PACKET_TOO_BIG, (byte) 0),
    HOP_LIMIT_EXCEEDED_IN_TRANSIT(Icmpv6Types.TIME_EXCEEDED, (byte) 0),
    FRAGMENT_REASSEMBLY_TIME_EXCEEDED(Icmpv6Types.TIME_EXCEEDED, (byte) 1),
    ERRONEOUS_HEADER_FIELD_ENCOUNTERED(Icmpv6Types.PARAMETER_PROBLEM, (byte) 0),
    UNRECOGNIZED_NEXT_HEADER_TYPE_ENCOUNTERED(Icmpv6Types.PARAMETER_PROBLEM, (byte) 1),
    UNRECOGNIZED_IPV6_OPTION_ENCOUNTERED(Icmpv6Types.PARAMETER_PROBLEM, (byte) 2),
    ECHO_REQUEST(Icmpv6Types.ECHO_REQUEST, (byte) 0),
    ECHO_RESPONSE(Icmpv6Types.ECHO_RESPONSE, (byte) 0),
    MULTICAST_LISTENER_QUERY(Icmpv6Types.MULTICAST_LISTENER_QUERY, (byte) 0),
    MULTICAST_LISTENER_REPORT(Icmpv6Types.MULTICAST_LISTENER_REPORT, (byte) 0),
    MULTICAST_LISTENER_DONE(Icmpv6Types.MULTICAST_LISTENER_DONE, (byte) 0),
    ROUTER_SOLICITATION(Icmpv6Types.ROUTER_SOLICITATION, (byte) 0),
    ROUTER_ADVERTISEMENT(Icmpv6Types.ROUTER_ADVERTISEMENT, (byte) 0),
    NEIGHBOR_SOLICITATION(Icmpv6Types.NEIGHBOR_SOLICITATION, (byte) 0),
    NEIGHBOR_ADVERTISEMENT(Icmpv6Types.NEIGHBOR_ADVERTISEMENT, (byte) 0),
    REDIRECT_MESSAGE(Icmpv6Types.REDIRECT_MESSAGE, (byte) 0),
    ROUTER_RENUMBERING_COMMAND(Icmpv6Types.ROUTER_RENUMBERING, (byte) 0),
    ROUTER_RENUMBERING_RESULT(Icmpv6Types.ROUTER_RENUMBERING, (byte) 1),
    SEQUENCE_NUMBER_RESET(Icmpv6Types.ROUTER_RENUMBERING, (byte) 255),
    DATA_FIELD_CONTAINS_AN_IPV6_ADDRESS_WHICH_IS_THE_SUBJECT_OF_THIS_QUERY(Icmpv6Types.ICMP_NODE_INFORMATION_QUERY, (byte) 0),
    DATA_FIELD_CONTAINS_A_NAME_WHICH_IS_THE_SUBJECT_OF_THIS_QUERY_OR_IS_EMPTY_AS_IN_THE_CASE_OF_A_NOOP(Icmpv6Types.ICMP_NODE_INFORMATION_QUERY, (byte) 1),
    DATA_FIELD_CONTAINS_AN_IPV4_ADDRESS_WHICH_IS_THE_SUBJECT_OF_THIS_QUERY(Icmpv6Types.ICMP_NODE_INFORMATION_QUERY, (byte) 2),
    SUCCESSFUL_REPLY_THE_REPLY_DATA_FIELD_MAY_OR_MAY_NOT_BE_EMPTY(Icmpv6Types.ICMP_NODE_INFORMATION_RESPONSE, (byte) 0),
    RESPONDER_REFUSES_TO_SUPPLY_THE_ANSWER_THE_REPLY_DATA_FIELD_WILL_BE_EMPTY(Icmpv6Types.ICMP_NODE_INFORMATION_RESPONSE, (byte) 1),
    QTYPE_OF_THE_QUERY_IS_UNKNOWN_TO_THE_RESPONDER_THE_REPLY_DATA_FIELD_WILL_BE_EMPTY(Icmpv6Types.ICMP_NODE_INFORMATION_RESPONSE, (byte) 2),
    INVERSE_NEIGHBOR_DISCOVERY_SOLICITATION_MESSAGE(Icmpv6Types.INVERSE_NEIGHBOR_DISCOVERY_SOLICITATION, (byte) 0),
    INVERSE_NEIGHBOR_DISCOVERY_ADVERTISEMENT_MESSAGE(Icmpv6Types.INVERSE_NEIGHBOR_DISCOVERY_ADVERTISEMENT, (byte) 0),
    MULTICAST_LISTENER_DISCOVERY_REPORTS(Icmpv6Types.MULTICAST_LISTENER_REPORT_V2, (byte) 0),
    HOME_AGENT_ADDRESS_DISCOVERY_REQUEST_MESSAGE(Icmpv6Types.HOME_AGENT_ADDRESS_DISCOVERY_REQUEST, (byte) 0),
    HOME_AGENT_ADDRESS_DISCOVERY_REPLY_MESSAGE(Icmpv6Types.HOME_AGENT_ADDRESS_DISCOVERY_REPLY, (byte) 0),
    MOBILE_PREFIX_SOLICITATION(Icmpv6Types.MOBILE_PREFIX_SOLICITATION, (byte) 0),
    MOBILE_PREFIX_ADVERTISEMENT(Icmpv6Types.MOBILE_PREFIX_ADVERTISEMENT, (byte) 0),
    CERTIFICATION_PATH_SOLICITATION(Icmpv6Types.CERTIFICATION_PATH_SOLICITATION, (byte) 0),
    CERTIFICATION_PATH_ADVERTISEMENT(Icmpv6Types.CERTIFICATION_PATH_ADVERTISEMENT, (byte) 0),
    MULTICAST_ROUTER_ADVERTISEMENT(Icmpv6Types.MULTICAST_ROUTER_ADVERTISEMENT, (byte) 0),
    MULTICAST_ROUTER_SOLICITATION(Icmpv6Types.MULTICAST_ROUTER_SOLICITATION, (byte) 0),
    MULTICAST_ROUTER_TERMINATION(Icmpv6Types.MULTICAST_ROUTER_TERMINATION, (byte) 0),
    DIS(Icmpv6Types.RPL, (byte) 0x00),
    DIO(Icmpv6Types.RPL, (byte) 0x01),
    DAO(Icmpv6Types.RPL, (byte) 0x02),
    DAO_ACK(Icmpv6Types.RPL, (byte) 0x03),
    SECURE_DIS(Icmpv6Types.RPL, (byte) 0x80),
    SECURE_DIO(Icmpv6Types.RPL, (byte) 0x81),
    SECURE_DAO(Icmpv6Types.RPL, (byte) 0x82),
    SECURE_DAO_ACK(Icmpv6Types.RPL, (byte) 0x83),
    CONSISTENCY_CHECK(Icmpv6Types.RPL, (byte) 0x8A),
    EXTENDED_ECHO_REQUEST(Icmpv6Types.EXTENDED_ECHO_REQUEST, (byte) 0),
    NO_ERROR(Icmpv6Types.EXTENDED_ECHO_REPLY, (byte) 0),
    MALFORMED_QUERY(Icmpv6Types.EXTENDED_ECHO_REPLY, (byte) 1),
    NO_SUCH_INTERFACE(Icmpv6Types.EXTENDED_ECHO_REPLY, (byte) 2),
    NO_SUCH_TABLE_ENTRY(Icmpv6Types.EXTENDED_ECHO_REPLY, (byte) 3),
    MULTIPLE_INTERFACES_SATISFY_QUERY(Icmpv6Types.EXTENDED_ECHO_REPLY, (byte) 4),;

    private final Icmpv6Type type;
    private final byte code;

    Icmpv6Codes(Icmpv6Type type, byte code) {
        this.type = type;
        this.code = code;
    }

    @Override
    public Icmpv6Type type() {
        return type;
    }

    @Override
    public byte code() {
        return code;
    }
}
