# This workflow will build a package using Gradle
# and push it to the Maven Central staging repository

name: Gradle publish

on: workflow_dispatch

jobs:
  publish-release:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Publish package
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_KEY: ${{ secrets.GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
